#!/bin/sh /etc/rc.common
START=93
STOP=12
USE_PROCD=1
start_service() {
    [ -e /dev/vboxguest ] || return 0
    procd_open_instance
    procd_set_param command /usr/sbin/VBoxService --foreground
    procd_set_param respawn 3600 5 5
    procd_set_param stderr 1
    procd_close_instance
}
