#!/bin/sh /etc/rc.common
START=96
STOP=9
USE_PROCD=1
start_service() {
    /usr/sbin/nginx -t -c /etc/serviceready/nginx.conf || return 1
    procd_open_instance
    procd_set_param command /usr/sbin/nginx -c /etc/serviceready/nginx.conf -g 'daemon off;'
    procd_set_param respawn 3600 5 5
    procd_set_param file /etc/serviceready/nginx.conf
    procd_set_param stderr 1
    procd_close_instance
}
reload_service() {
    /usr/sbin/nginx -t -c /etc/serviceready/nginx.conf && /usr/sbin/nginx -c /etc/serviceready/nginx.conf -s reload
}
